---
- name: Установить ufw
  apt:
    name: ufw
    state: present
    update_cache: yes
  tags: [firewall, install]
  when: enable_firewall | default(false)

- name: Включить ufw (через блок)
  block:
    - name: Активировать ufw (с ошибкой)
      command: ufw --force eneble

    - name: Разрешить SSH
      command: ufw allow 22

  rescue:
    - name: Лог ошибки
      debug:
        msg: "‼️ Не удалось включить ufw — произошла ошибка"

  tags: [firewall, rules]
  when: enable_firewall | default(false)
