---
- name: Установить ufw
  apt:
    name: ufw
    state: present
    update_cache: yes
  tags: [firewall, install]
  when: enable_firewall | default(false)

- name: Выключить ufw, если отключение включено
  command: ufw disable
  when: enable_firewall | default(false) == false
  tags: [firewall, disable]

- name: Включить и настроить ufw (через блок)
  block:
    - name: Установить политику по умолчанию (deny)
      command: ufw default deny incoming
      changed_when: false

    - name: Разрешить нужные порты
      command: "ufw allow {{ item }}"
      loop: "{{ open_ports }}"
      when: enable_firewall | default(false)
      tags: [firewall, rules]

    - name: Включить ufw
      command: ufw --force enable
      tags: [firewall, enable]

  rescue:
    - debug:
        msg: "‼️ Не удалось включить ufw"

  always:
    - debug:
        msg: "✅ Завершение настройки ufw"

  when: enable_firewall | default(false)
  tags: [firewall, rules]

- name: Показать статус ufw
  command: ufw status
  register: ufw_status
  changed_when: false
  tags: [firewall, status]

- name: Вывести статус UFW
  debug:
    var: ufw_status.stdout
  tags: [firewall, status]
