---
- name: Debug API key (не для продакшена)
  debug:
    msg: "API Key is {{ ansible_password }}"
  no_log: false  # временно выключаем сокрытие, чтобы увидеть в stdout

- name: Считать список установленных пакетов
  package_facts:
    manager: auto
  tags: [facts]

- name: Установить список пакетов
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - htop
    - curl
    - net-tools
    - git
  notify: Restart nginx
  tags: [packages]

- name: Остановить nginx, если установлен
  service:
    name: nginx
    state: stopped
  when: "'nginx' in ansible_facts.packages"
  notify: Restart nginx
  tags: [nginx]
