---
- name: Nginx with template
  hosts: all
  become: yes

  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove nginx if requested
      apt:
      name: nginx
      state: absent
      when: remove_nginx | default(false)
      tags: [remove]

    - name: Place templated index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
